/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The API process is running. */
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The API can serve requests: its database answers. 503 database-unavailable when it does not. */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/tax-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every tax year the API holds a configuration for, oldest first. */
        get: operations["listTaxYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/tax-years/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One tax year's configuration: its hash, regions and declared gaps. */
        get: operations["getTaxYear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/set-aside/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs the set-aside estimator on the console's input file for a tax year. */
        post: operations["estimateSetAside"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stores the user's class for a movement. A later call replaces an earlier one. */
        post: operations["classifyTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The stored profiles: none before the first is created, one after. */
        get: operations["listProfiles"];
        put?: never;
        /** Stores the profile. Local mode keeps one: a second is refused with 409. */
        post: operations["createProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One stored profile. */
        get: operations["getProfile"];
        /** Replaces a stored profile with the one in the body. */
        put: operations["replaceProfile"];
        post?: never;
        /** Deletes the profile and everything stored for it. Nothing is kept: export it first to keep a copy. */
        delete: operations["deleteProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything stored for the profile, in one versioned document (SPEC-009 §2.1). Personal financial data: sent with Cache-Control: no-store. */
        get: operations["exportProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restores an export (SPEC-009 §2.1) into an empty installation. The same file again changes nothing; anything else stored is a 409. */
        post: operations["restoreProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/set-aside/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs the set-aside estimator on a stored profile for a quarter of its tax year, its classified movements giving the actuals of the closed quarters. */
        get: operations["estimateSetAsideForProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every obligation of the profile's tax year, in due-date order: Modelo 130, 303 and 349, the monthly TGSS cuota and the Renta true-up. */
        get: operations["calendarForProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The upcoming calendar as an RFC 5545 export; amounts=true adds each obligation's known amount to its title, lang picks the event text's language. */
        get: operations["calendarForProfileAsIcs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/bank-statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Imports a bank statement, the file itself as the body. A line an earlier import stored is not stored again. */
        post: operations["importBankStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The stored movements in booking-date order: all of them, a year's, or a quarter's of that year. */
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The movements of the profile's tax year waiting for the user's class, unclear or with a rule's suggestion, in the transactions list's order. */
        get: operations["getReviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/calculations/quarter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs the set-aside estimator on a stored profile and returns one quarter's Modelo 130, its casillas and trace. */
        post: operations["calculateQuarter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/calculations/annual-true-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs the set-aside estimator on a stored profile and returns the annual true-up gap, due window and trace. */
        post: operations["calculateAnnualTrueUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityDocument: {
            retenciones: components["schemas"]["RetencionesDocument"];
            actuals: components["schemas"]["QuarterToDateDocument"][];
            projection: components["schemas"]["ProjectionDocument"];
        };
        AnnualTrueUpView: {
            /** Format: int32 */
            taxYear: number;
            configHash: string;
            liabilityOnActivity: string;
            marginalRate: string;
            reduccionTrabajoLost: string;
            gap: string;
            /** Format: date */
            dueFrom: string;
            /** Format: date */
            dueBy: string;
            payableIn: string;
            trace: components["schemas"]["TraceStepView"][];
            notices: components["schemas"]["NoticeView"][];
        };
        BankStatementImport: {
            bank: string;
            /** Format: int32 */
            lines: number;
            /** Format: int32 */
            imported: number;
            /** Format: int32 */
            alreadyImported: number;
        };
        CasillaView: {
            key: string;
            amount: string;
        };
        DeclaredGap: {
            entry: string;
            note: string;
        };
        EmploymentDocument: {
            ingresos: string;
            seguridadSocial: string;
        };
        EntityCounts: {
            /** Format: int32 */
            profiles: number;
            /** Format: int32 */
            bankTransactions: number;
        };
        ExportedBankTransaction: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            bookingDate: string;
            /** Format: date */
            valueDate: string;
            description: string;
            amount: string;
            balance: null | string;
            /** Format: int32 */
            importSequence: number;
            /** Format: int32 */
            lineNumber: number;
            lineKey: string;
            class: null | components["schemas"]["TransactionClass"];
        };
        ExportedEntities: {
            profiles: components["schemas"]["ProfileView"][];
            bankTransactions: components["schemas"]["ExportedBankTransaction"][];
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        LedgerView: {
            actualsThrough: null | components["schemas"]["Quarter"];
            /** Format: int32 */
            counted: number;
            /** Format: int32 */
            awaitingReview: number;
            /** Format: int32 */
            awaitingInvoice: number;
        };
        NewActivityChoice: components["schemas"]["NewActivityChoiceEstablishedActivity"] | components["schemas"]["NewActivityChoiceNewActivityStarted"];
        NewActivityChoiceEstablishedActivity: {
            /** @enum {string} */
            kind?: "established";
        };
        NewActivityChoiceNewActivityStarted: {
            /** @enum {string} */
            kind?: "started";
            period: components["schemas"]["StartedPeriod"];
            ingresosFromFormerEmployer: string;
        };
        NewActivityDocument: "established" | {
            /** @enum {string} */
            period: "first" | "following";
            ingresosFromFormerEmployer: string;
        };
        NextModelo130: {
            quarter: components["schemas"]["Quarter"];
            aIngresar: string;
            /** Format: date */
            dueFrom: string;
            /** Format: date */
            dueBy: string;
        };
        NoticeView: {
            code: string;
            severity: components["schemas"]["WarningSeverity"];
            text: string;
        };
        ObligationAmountView: components["schemas"]["ObligationAmountViewKnownAmount"] | components["schemas"]["ObligationAmountViewNotYetKnownAmount"];
        ObligationAmountViewKnownAmount: {
            /** @enum {string} */
            kind?: "known";
            euros: string;
        };
        ObligationAmountViewNotYetKnownAmount: {
            /** @enum {string} */
            kind?: "notYetKnown";
            reason: string;
        };
        /** @enum {unknown} */
        ObligationKind: "Modelo130" | "Modelo303" | "Modelo349" | "SeguridadSocial" | "RentaTrueUp";
        ObligationView: {
            kind: components["schemas"]["ObligationKind"];
            period: string;
            /** Format: date */
            dueFrom: string;
            /** Format: date */
            dueBy: string;
            amount: components["schemas"]["ObligationAmountView"];
        };
        PaymentsCalendarView: {
            /** Format: int32 */
            taxYear: number;
            configHash: string;
            modelo349QuarterlyFilingCap: string;
            obligations: components["schemas"]["ObligationView"][];
        };
        PreviousYearChoice: components["schemas"]["PreviousYearChoiceNoActivityLastYear"] | components["schemas"]["PreviousYearChoicePreviousYearNet"];
        PreviousYearChoiceNoActivityLastYear: {
            /** @enum {string} */
            kind?: "noActivity";
        };
        PreviousYearChoicePreviousYearNet: {
            /** @enum {string} */
            kind?: "rendimientoNeto";
            rendimientoNeto: string;
        };
        PreviousYearDocument: "noActivity" | {
            rendimientoNeto: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        ProfileDocument: {
            region: string;
            employment: components["schemas"]["EmploymentDocument"];
            activity: components["schemas"]["RegistrationDocument"];
        };
        ProfileEmployment: {
            ingresos: string;
            seguridadSocial: string;
        };
        ProfileExport: {
            format: string;
            /** Format: int32 */
            formatVersion: number;
            classification: string;
            /** Format: date-time */
            exportedAt: string;
            entities: components["schemas"]["ExportedEntities"];
        };
        ProfileInputDocument: {
            /** Format: int32 */
            taxYear: number;
            region: string;
            employment: components["schemas"]["ProfileEmployment"];
            activity: components["schemas"]["ProfileRegistration"];
            projection: components["schemas"]["ProfileProjection"];
        };
        ProfileProjection: {
            ingresos: string;
            gastos: string;
            baseCotizacion: string;
        };
        ProfileRegistration: {
            /** Format: date */
            alta: string;
            previousYear: components["schemas"]["PreviousYearChoice"];
            newActivity: components["schemas"]["NewActivityChoice"];
        };
        ProfileView: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            taxYear: number;
            region: string;
            employment: components["schemas"]["ProfileEmployment"];
            activity: components["schemas"]["ProfileRegistration"];
            projection: components["schemas"]["ProfileProjection"];
        };
        ProjectionDocument: {
            ingresos: string;
            gastos: string;
            baseCotizacion: string;
        };
        /** @enum {unknown} */
        Quarter: "Q1" | "Q2" | "Q3" | "Q4";
        QuarterResultView: {
            /** Format: int32 */
            taxYear: number;
            configHash: string;
            quarter: components["schemas"]["Quarter"];
            aIngresar: string;
            /** Format: date */
            dueFrom: string;
            /** Format: date */
            dueBy: string;
            casillas: components["schemas"]["CasillaView"][];
            trace: components["schemas"]["TraceStepView"][];
        };
        QuarterToDateDocument: {
            quarter: components["schemas"]["Quarter"];
            ingresosYtd: string;
            gastosYtd: string;
            cuotasSsYtd: string;
        };
        RegionView: {
            code: string;
            name: string;
        };
        RegistrationDocument: {
            /** Format: date */
            alta: string;
            previousYear: components["schemas"]["PreviousYearDocument"];
            newActivity: components["schemas"]["NewActivityDocument"];
        };
        RestoredExport: {
            /** Format: uuid */
            profileId: string;
            entities: components["schemas"]["EntityCounts"];
        };
        /** @enum {unknown} */
        RetencionesDocument: "foreignPayersOnly";
        ReviewItem: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            bookingDate: string;
            /** Format: date */
            valueDate: string;
            description: string;
            amount: string;
            suggestion: null | components["schemas"]["ReviewSuggestion"];
        };
        ReviewSuggestion: {
            class: components["schemas"]["TransactionClass"];
            ruleId: string;
        };
        SetAsideEstimate: {
            /** Format: int32 */
            taxYear: number;
            configHash: string;
            holdBackShare: string;
            nextPayment: components["schemas"]["NextModelo130"];
            monthlyCuotaSs: string;
            annualTrueUpGap: string;
            annualTrueUpPayableIn: string;
            ivaToSetAside: string;
            trace: components["schemas"]["TraceStepView"][];
            notices: components["schemas"]["NoticeView"][];
            ledger: null | components["schemas"]["LedgerView"];
        };
        /** @description The console's input file, byte for byte: src/GestorIA.Cli/README.md describes every field. */
        SetAsideInputDocument: {
            asOf: components["schemas"]["Quarter"];
            profile: components["schemas"]["ProfileDocument"];
            activity: components["schemas"]["ActivityDocument"];
        };
        /** @enum {unknown} */
        StartedPeriod: "first" | "following";
        TaxYearView: {
            /** Format: int32 */
            taxYear: number;
            configHash: string;
            regions: components["schemas"]["RegionView"][];
            gaps: components["schemas"]["DeclaredGap"][];
            modelo130Lines: {
                [key: string]: string;
            };
        };
        TraceInputView: {
            name: string;
            value: string;
        };
        TraceOutputView: {
            kind: components["schemas"]["TraceValueKind"];
            value: string;
        };
        /** @enum {unknown} */
        TraceSection: "Trabajo" | "Actividad" | "Ahorro" | "Inmuebles" | "Bases" | "Minimo" | "Cuota" | "Deducciones" | "Resultado" | "SeguridadSocial" | "Modelo130";
        TraceStepView: {
            id: string;
            section: components["schemas"]["TraceSection"];
            title: string;
            inputs: components["schemas"]["TraceInputView"][];
            formula: string;
            output: components["schemas"]["TraceOutputView"];
            reference: string;
        };
        /** @enum {unknown} */
        TraceValueKind: "money" | "rate" | "count" | "date";
        /** @enum {unknown} */
        TransactionClass: "activityIncome" | "deductibleExpense" | "socialSecurity" | "aeatPayment" | "employmentIncome" | "savingsIncome" | "ownTransfer" | "personal";
        TransactionClassification: {
            class: components["schemas"]["TransactionClass"];
        };
        TransactionView: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            bookingDate: string;
            /** Format: date */
            valueDate: string;
            description: string;
            amount: string;
            balance: null | string;
        };
        /** @enum {unknown} */
        WarningSeverity: "Info" | "Warning" | "Error";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listTaxYears: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxYearView"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTaxYear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxYearView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    estimateSetAside: {
        parameters: {
            query: {
                taxYear: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAsideInputDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetAsideEstimate"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    classifyTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionClassification"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInputDocument"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    replaceProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInputDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    exportProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileExport"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    restoreProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description An export file (SPEC-009 §2.1), at most 16777216 bytes. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileExport"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoredExport"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoredExport"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    estimateSetAsideForProfile: {
        parameters: {
            query: {
                asOf: components["schemas"]["Quarter"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetAsideEstimate"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    calendarForProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentsCalendarView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    calendarForProfileAsIcs: {
        parameters: {
            query?: {
                amounts?: boolean;
                lang?: "uk" | "es" | "en" | "ru";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    importBankStatement: {
        parameters: {
            query: {
                bank: "bbva";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description The statement file as exported by the bank, at most 2097152 bytes. */
        requestBody: {
            content: {
                "text/csv": string;
                "text/plain": string;
                "application/vnd.ms-excel": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankStatementImport"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                year?: number;
                /** @description Needs year. */
                quarter?: components["schemas"]["Quarter"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionView"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getReviewQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItem"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    calculateQuarter: {
        parameters: {
            query?: {
                quarter?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarterResultView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    calculateAnnualTrueUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnualTrueUpView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
