/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/tax-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every tax year the API holds a configuration for, oldest first. */
        get: operations["listTaxYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/tax-years/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One tax year's configuration: its hash, regions and declared gaps. */
        get: operations["getTaxYear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/set-aside/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs the set-aside estimator on the console's input file for a tax year. */
        post: operations["estimateSetAside"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The stored profiles: none before the first is created, one after. */
        get: operations["listProfiles"];
        put?: never;
        /** Stores the profile. Local mode keeps one: a second is refused with 409. */
        post: operations["createProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One stored profile. */
        get: operations["getProfile"];
        /** Replaces a stored profile with the one in the body. */
        put: operations["replaceProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{id}/set-aside/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs the set-aside estimator on a stored profile for a quarter of its tax year, with no closed quarter stated. */
        get: operations["estimateSetAsideForProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityDocument: {
            retenciones: components["schemas"]["RetencionesDocument"];
            actuals: components["schemas"]["QuarterToDateDocument"][];
            projection: components["schemas"]["ProjectionDocument"];
        };
        DeclaredGap: {
            entry: string;
            note: string;
        };
        EmploymentDocument: {
            ingresos: string;
            seguridadSocial: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        NewActivityChoice: components["schemas"]["NewActivityChoiceEstablishedActivity"] | components["schemas"]["NewActivityChoiceNewActivityStarted"];
        NewActivityChoiceEstablishedActivity: {
            /** @enum {string} */
            kind?: "established";
        };
        NewActivityChoiceNewActivityStarted: {
            /** @enum {string} */
            kind?: "started";
            period: components["schemas"]["StartedPeriod"];
            ingresosFromFormerEmployer: string;
        };
        NewActivityDocument: "established" | {
            /** @enum {string} */
            period: "first" | "following";
            ingresosFromFormerEmployer: string;
        };
        NextModelo130: {
            quarter: components["schemas"]["Quarter"];
            aIngresar: string;
            /** Format: date */
            dueFrom: string;
            /** Format: date */
            dueBy: string;
        };
        NoticeView: {
            code: string;
            severity: components["schemas"]["WarningSeverity"];
            text: string;
        };
        PreviousYearChoice: components["schemas"]["PreviousYearChoiceNoActivityLastYear"] | components["schemas"]["PreviousYearChoicePreviousYearNet"];
        PreviousYearChoiceNoActivityLastYear: {
            /** @enum {string} */
            kind?: "noActivity";
        };
        PreviousYearChoicePreviousYearNet: {
            /** @enum {string} */
            kind?: "rendimientoNeto";
            rendimientoNeto: string;
        };
        PreviousYearDocument: "noActivity" | {
            rendimientoNeto: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        ProfileDocument: {
            region: string;
            employment: components["schemas"]["EmploymentDocument"];
            activity: components["schemas"]["RegistrationDocument"];
        };
        ProfileEmployment: {
            ingresos: string;
            seguridadSocial: string;
        };
        ProfileInputDocument: {
            /** Format: int32 */
            taxYear: number;
            region: string;
            employment: components["schemas"]["ProfileEmployment"];
            activity: components["schemas"]["ProfileRegistration"];
            projection: components["schemas"]["ProfileProjection"];
        };
        ProfileProjection: {
            ingresos: string;
            gastos: string;
            baseCotizacion: string;
        };
        ProfileRegistration: {
            /** Format: date */
            alta: string;
            previousYear: components["schemas"]["PreviousYearChoice"];
            newActivity: components["schemas"]["NewActivityChoice"];
        };
        ProfileView: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            taxYear: number;
            region: string;
            employment: components["schemas"]["ProfileEmployment"];
            activity: components["schemas"]["ProfileRegistration"];
            projection: components["schemas"]["ProfileProjection"];
        };
        ProjectionDocument: {
            ingresos: string;
            gastos: string;
            baseCotizacion: string;
        };
        /** @enum {unknown} */
        Quarter: "Q1" | "Q2" | "Q3" | "Q4";
        QuarterToDateDocument: {
            quarter: components["schemas"]["Quarter"];
            ingresosYtd: string;
            gastosYtd: string;
            cuotasSsYtd: string;
        };
        RegionView: {
            code: string;
            name: string;
        };
        RegistrationDocument: {
            /** Format: date */
            alta: string;
            previousYear: components["schemas"]["PreviousYearDocument"];
            newActivity: components["schemas"]["NewActivityDocument"];
        };
        /** @enum {unknown} */
        RetencionesDocument: "foreignPayersOnly";
        SetAsideEstimate: {
            /** Format: int32 */
            taxYear: number;
            configHash: string;
            holdBackShare: string;
            nextPayment: components["schemas"]["NextModelo130"];
            monthlyCuotaSs: string;
            annualTrueUpGap: string;
            annualTrueUpPayableIn: string;
            ivaToSetAside: string;
            trace: components["schemas"]["TraceStepView"][];
            notices: components["schemas"]["NoticeView"][];
        };
        /** @description The console's input file, byte for byte: src/GestorIA.Cli/README.md describes every field. */
        SetAsideInputDocument: {
            asOf: components["schemas"]["Quarter"];
            profile: components["schemas"]["ProfileDocument"];
            activity: components["schemas"]["ActivityDocument"];
        };
        /** @enum {unknown} */
        StartedPeriod: "first" | "following";
        TaxYearView: {
            /** Format: int32 */
            taxYear: number;
            configHash: string;
            regions: components["schemas"]["RegionView"][];
            gaps: components["schemas"]["DeclaredGap"][];
        };
        TraceInputView: {
            name: string;
            value: string;
        };
        TraceOutputView: {
            kind: components["schemas"]["TraceValueKind"];
            value: string;
        };
        /** @enum {unknown} */
        TraceSection: "Trabajo" | "Actividad" | "Ahorro" | "Inmuebles" | "Bases" | "Minimo" | "Cuota" | "Deducciones" | "Resultado" | "SeguridadSocial" | "Modelo130";
        TraceStepView: {
            id: string;
            section: components["schemas"]["TraceSection"];
            title: string;
            inputs: components["schemas"]["TraceInputView"][];
            formula: string;
            output: components["schemas"]["TraceOutputView"];
            reference: string;
        };
        /** @enum {unknown} */
        TraceValueKind: "money" | "rate" | "count" | "date";
        /** @enum {unknown} */
        WarningSeverity: "Info" | "Warning" | "Error";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTaxYears: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxYearView"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTaxYear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxYearView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    estimateSetAside: {
        parameters: {
            query: {
                taxYear: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAsideInputDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetAsideEstimate"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInputDocument"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    replaceProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInputDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    estimateSetAsideForProfile: {
        parameters: {
            query: {
                asOf: components["schemas"]["Quarter"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetAsideEstimate"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
