// <auto-generated />
using System;
using GestorIA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorIA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GestoriaDbContext))]
    [Migration("20260927164529_Profiles")]
    partial class Profiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorIA.Infrastructure.Profiles.ProfileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Alta")
                        .HasColumnType("date");

                    b.Property<decimal>("BaseCotizacion")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("EmploymentIngresos")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("EmploymentSeguridadSocial")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("IngresosFromFormerEmployer")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("NewActivityPeriod")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<decimal?>("PreviousYearRendimientoNeto")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("ProjectionGastos")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("ProjectionIngresos")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Singleton")
                        .IsUnique();

                    b.ToTable("Profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profiles_NewActivity", "(\"NewActivityPeriod\" IS NULL) = (\"IngresosFromFormerEmployer\" IS NULL)");

                            t.HasCheckConstraint("CK_Profiles_Singleton", "\"Singleton\"");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
