// <auto-generated />
using System;
using GestorIA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorIA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GestoriaDbContext))]
    [Migration("20260929115546_StatementImports")]
    partial class StatementImports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorIA.Infrastructure.Profiles.ProfileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Alta")
                        .HasColumnType("date");

                    b.Property<decimal>("BaseCotizacion")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("EmploymentIngresos")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("EmploymentSeguridadSocial")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("IngresosFromFormerEmployer")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("NewActivityPeriod")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<decimal?>("PreviousYearRendimientoNeto")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("ProjectionGastos")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("ProjectionIngresos")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Singleton")
                        .IsUnique();

                    b.ToTable("Profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profiles_NewActivity", "(\"NewActivityPeriod\" IS NULL) = (\"IngresosFromFormerEmployer\" IS NULL)");

                            t.HasCheckConstraint("CK_Profiles_Singleton", "\"Singleton\"");
                        });
                });

            modelBuilder.Entity("GestorIA.Infrastructure.Transactions.BankTransactionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Balance")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("Class")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImportSequence")
                        .HasColumnType("integer");

                    b.Property<string>("LineKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "BookingDate");

                    b.HasIndex("ProfileId", "ImportSequence");

                    b.HasIndex("ProfileId", "LineKey")
                        .IsUnique();

                    b.ToTable("BankTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_BankTransactions_Class", "\"Class\" IS NULL OR \"Class\" IN ('ActivityIncome', 'DeductibleExpense', 'SocialSecurity', 'AeatPayment', 'EmploymentIncome', 'SavingsIncome', 'OwnTransfer', 'Personal')");
                        });
                });

            modelBuilder.Entity("GestorIA.Infrastructure.Transactions.StatementImportRow", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.HasKey("ProfileId", "Sequence");

                    b.ToTable("StatementImports", null, t =>
                        {
                            t.HasCheckConstraint("CK_StatementImports_Period", "\"From\" <= \"To\"");
                        });
                });

            modelBuilder.Entity("GestorIA.Infrastructure.Transactions.BankTransactionRow", b =>
                {
                    b.HasOne("GestorIA.Infrastructure.Profiles.ProfileRow", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorIA.Infrastructure.Transactions.StatementImportRow", null)
                        .WithMany()
                        .HasForeignKey("ProfileId", "ImportSequence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorIA.Infrastructure.Transactions.StatementImportRow", b =>
                {
                    b.HasOne("GestorIA.Infrastructure.Profiles.ProfileRow", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
